-- SIGESS Database Schema Dump (Fiel à Colônia Z-2 de Salvaterra)
-- Generated by Antigravity using Supabase MCP

-- 1. EXTENSIONS
CREATE EXTENSION IF NOT EXISTS "uuid-ossp" WITH SCHEMA "extensions";
CREATE EXTENSION IF NOT EXISTS "pgcrypto" WITH SCHEMA "extensions";

-- 2. FUNCTIONS
CREATE OR REPLACE FUNCTION public.update_updated_at_column()
 RETURNS trigger
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public', 'pg_temp'
AS $function$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$function$;

CREATE OR REPLACE FUNCTION public.check_member_limit()
 RETURNS trigger
 LANGUAGE plpgsql
 SECURITY DEFINER
AS $function$
DECLARE
    v_max_socios INTEGER;
    v_current_count INTEGER;
BEGIN
    SELECT max_socios INTO v_max_socios FROM public."User" WHERE id = auth.uid();
    IF v_max_socios IS NULL THEN RETURN NEW; END IF;
    SELECT count(*) INTO v_current_count FROM public.socios;
    IF v_current_count >= v_max_socios THEN
        RAISE EXCEPTION 'limite_cadastros: Limite de % sócios atingido.', v_max_socios;
    END IF;
    RETURN NEW;
END; $function$;

CREATE OR REPLACE FUNCTION public.generate_next_codigo_localidade()
 RETURNS trigger
 LANGUAGE plpgsql
AS $function$
DECLARE
  max_code_val integer;
  next_code text;
BEGIN
  SELECT COALESCE(MAX(NULLIF(regexp_replace(codigo_localidade, '\D', '', 'g'), '')::integer), 0) INTO max_code_val FROM public.localidades;
  next_code := LPAD((max_code_val + 1)::text, 3, '0');
  IF (NEW.codigo_localidade IS NULL) OR (NEW.codigo_localidade = '') THEN
    NEW.codigo_localidade := next_code;
  END IF;
  RETURN NEW;
END; $function$;

CREATE OR REPLACE FUNCTION public.handle_delete_user()
 RETURNS trigger
 LANGUAGE plpgsql
 SECURITY DEFINER
AS $function$
BEGIN
  DELETE FROM public."User" WHERE id = OLD.id;
  RETURN OLD;
END; $function$;

CREATE OR REPLACE FUNCTION public.handle_new_user()
 RETURNS trigger
 LANGUAGE plpgsql
 SECURITY DEFINER
AS $function$
BEGIN
  INSERT INTO public."User" (id, email, role)
  VALUES (NEW.id, NEW.email, 'user');
  RETURN NEW;
END; $function$;

CREATE OR REPLACE FUNCTION public.handle_update_user()
 RETURNS trigger
 LANGUAGE plpgsql
 SECURITY DEFINER
AS $function$
BEGIN
  UPDATE public."User" SET email = NEW.email WHERE id = NEW.id;
  RETURN NEW;
END; $function$;

CREATE OR REPLACE FUNCTION public.get_next_cod_req()
 RETURNS text
 LANGUAGE plpgsql
AS $function$
DECLARE
    next_code INTEGER;
    formatted_code TEXT;
BEGIN
    LOCK TABLE requerimentos IN EXCLUSIVE MODE;
    SELECT COALESCE(
        MAX(CAST(cod_req AS INTEGER)), 
        0
    ) + 1 
    INTO next_code
    FROM requerimentos 
    WHERE cod_req ~ '^[0-9]+$';
    formatted_code := LPAD(next_code::text, 6, '0');
    RETURN formatted_code;
END;
$function$;

CREATE OR REPLACE FUNCTION public.auto_generate_cod_req()
 RETURNS trigger
 LANGUAGE plpgsql
 AS $function$
BEGIN
    IF (NEW.cod_req IS NULL) OR (NEW.cod_req = '') THEN
        NEW.cod_req := get_next_cod_req();
    END IF;
    RETURN NEW;
END;
$function$;

CREATE OR REPLACE FUNCTION public.socio_inadimplente_ano(p_cpf text, p_ano integer)
 RETURNS boolean
 LANGUAGE plpgsql
 STABLE SECURITY DEFINER
AS $function$
DECLARE
  v_isento        boolean;
  v_regime        text;
  v_ano_base      integer;
  v_tem_pagamento boolean;
BEGIN
  SELECT COALESCE(isento, false) INTO v_isento
  FROM public.financeiro_config_socio WHERE cpf = p_cpf;
  IF v_isento THEN RETURN false; END IF;

  SELECT ano_base_cobranca INTO v_ano_base FROM public.parametros_financeiros LIMIT 1;
  IF p_ano < v_ano_base THEN RETURN false; END IF;

  SELECT COALESCE(cfg.regime, pf.regime_padrao)
  INTO v_regime
  FROM public.parametros_financeiros pf
  LEFT JOIN public.financeiro_config_socio cfg ON cfg.cpf = p_cpf
  LIMIT 1;

  IF v_regime = 'anuidade' THEN
    SELECT EXISTS(
      SELECT 1 FROM public.financeiro_lancamentos
      WHERE socio_cpf = p_cpf AND tipo = 'anuidade'
        AND competencia_ano = p_ano AND status = 'pago'
    ) INTO v_tem_pagamento;
  ELSE
    SELECT NOT EXISTS(
      SELECT 1 FROM generate_series(1, EXTRACT(MONTH FROM CURRENT_DATE)::int) m
      WHERE NOT EXISTS (
        SELECT 1 FROM public.financeiro_lancamentos
        WHERE socio_cpf = p_cpf AND tipo = 'mensalidade'
          AND competencia_ano = p_ano AND competencia_mes = m AND status = 'pago'
      )
    ) INTO v_tem_pagamento;
  END IF;

  RETURN NOT v_tem_pagamento;
END;
$function$;

CREATE OR REPLACE FUNCTION public.launch_bulk_contribution(p_tipo_cobranca_id uuid)
 RETURNS integer
 LANGUAGE plpgsql
 SECURITY DEFINER
AS $function$
DECLARE
  v_valor numeric(10,2);
  v_count integer := 0;
BEGIN
  SELECT valor_padrao INTO v_valor
  FROM public.tipos_cobranca
  WHERE id = p_tipo_cobranca_id
    AND categoria = 'contribuicao'
    AND obrigatoriedade = 'compulsoria'
    AND ativo = true;

  IF v_valor IS NULL THEN
    RAISE EXCEPTION 'Tipo de cobrança inválido ou sem valor padrão definido';
  END IF;

  INSERT INTO public.financeiro_cobrancas_geradas (tipo_cobranca_id, socio_cpf, valor)
  SELECT p_tipo_cobranca_id, s.cpf, v_valor
  FROM public.socios s
  WHERE s.situacao = 'ATIVO'
    AND NOT EXISTS (
      SELECT 1 FROM public.financeiro_cobrancas_geradas cg
      WHERE cg.tipo_cobranca_id = p_tipo_cobranca_id
        AND cg.socio_cpf = s.cpf
    );

  GET DIAGNOSTICS v_count = ROW_COUNT;
  RETURN v_count;
END;
$function$;

CREATE OR REPLACE FUNCTION public.update_member_regime(p_cpf text, p_novo_regime text, p_observacao text DEFAULT NULL::text)
 RETURNS void
 LANGUAGE plpgsql
 SECURITY DEFINER
AS $function$
DECLARE
  v_user_id uuid := auth.uid();
BEGIN
  UPDATE public.financeiro_historico_regime
  SET vigente_ate = CURRENT_DATE
  WHERE socio_cpf = p_cpf AND vigente_ate IS NULL;

  INSERT INTO public.financeiro_historico_regime (socio_cpf, regime, vigente_desde, alterado_por, observacao)
  VALUES (p_cpf, p_novo_regime, CURRENT_DATE, v_user_id, p_observacao);

  INSERT INTO public.financeiro_config_socio (cpf, regime)
  VALUES (p_cpf, p_novo_regime)
  ON CONFLICT (cpf)
  DO UPDATE SET regime = p_novo_regime, updated_at = now();
END;
$function$;

CREATE OR REPLACE FUNCTION public.register_payment_session(p_socio_cpf text, p_sessao_id uuid, p_forma_pagamento text, p_data_pagamento date, p_itens jsonb, p_daes jsonb DEFAULT '[]'::jsonb)
 RETURNS void
 LANGUAGE plpgsql
 SECURITY DEFINER
AS $function$
DECLARE
  v_item jsonb;
  v_dae jsonb;
  v_daes_array jsonb := COALESCE(p_daes, '[]'::jsonb);
  v_user_id uuid := auth.uid();
  v_grupo_id uuid := NULL;
BEGIN
  IF jsonb_array_length(v_daes_array) > 0 THEN
    IF (v_daes_array->0->>'tipo_boleto') != 'unitario' THEN
       v_grupo_id := gen_random_uuid();
    END IF;
  END IF;

  FOR v_item IN SELECT * FROM jsonb_array_elements(p_itens)
  LOOP
    INSERT INTO public.financeiro_lancamentos (
      socio_cpf, sessao_id, tipo, valor, forma_pagamento,
      data_pagamento, competencia_ano, competencia_mes,
      tipo_cobranca_id, descricao, registrado_por
    ) VALUES (
      p_socio_cpf, p_sessao_id, (v_item->>'tipo'), (v_item->>'valor')::numeric,
      p_forma_pagamento, p_data_pagamento, (v_item->>'competencia_ano')::integer,
      (v_item->>'competencia_mes')::integer,
      CASE WHEN (v_item->>'tipo_cobranca_id') = '' THEN NULL ELSE (v_item->>'tipo_cobranca_id')::uuid END,
      (v_item->>'descricao'), v_user_id
    );

    IF (v_item->>'tipo_cobranca_id') IS NOT NULL AND (v_item->>'tipo_cobranca_id') != '' THEN
      UPDATE public.financeiro_cobrancas_geradas
      SET status = 'pago', lancamento_id = (
        SELECT id FROM public.financeiro_lancamentos
        WHERE sessao_id = p_sessao_id AND tipo_cobranca_id = (v_item->>'tipo_cobranca_id')::uuid
        ORDER BY created_at DESC LIMIT 1
      ), updated_at = now()
      WHERE socio_cpf = p_socio_cpf
        AND tipo_cobranca_id = (v_item->>'tipo_cobranca_id')::uuid
        AND status = 'pendente';
    END IF;
  END LOOP;

  FOR v_dae IN SELECT * FROM jsonb_array_elements(v_daes_array)
  LOOP
    INSERT INTO public.financeiro_dae (
      socio_cpf, sessao_id, tipo_boleto, competencia_ano,
      competencia_mes, valor, forma_pagamento, registrado_por,
      data_recebimento, grupo_id
    ) VALUES (
      p_socio_cpf, p_sessao_id, (v_dae->>'tipo_boleto'),
      (v_dae->>'competencia_ano')::integer, (v_dae->>'competencia_mes')::integer,
      (v_dae->>'valor')::numeric, p_forma_pagamento, v_user_id,
      p_data_pagamento,
      CASE WHEN (v_dae->>'tipo_boleto') = 'unitario' THEN NULL ELSE v_grupo_id END
    );
  END LOOP;
END;
$function$;

CREATE OR REPLACE FUNCTION public.confirmar_upload_foto(p_token uuid, p_base64 text)
 RETURNS boolean
 LANGUAGE plpgsql
 SECURITY DEFINER
 AS $function$
BEGIN
  UPDATE public.foto_upload_tokens
  SET 
    foto_base64 = p_base64,
    updated_at = now()
  WHERE token = p_token
    AND expires_at > now()
    AND foto_base64 IS NULL;

  RETURN FOUND;
END;
$function$;

CREATE OR REPLACE FUNCTION public.update_dae_group(p_grupo_id uuid, p_new_year integer, p_items jsonb)
 RETURNS void
 LANGUAGE plpgsql
 SECURITY DEFINER
AS $function$
DECLARE
  v_novo_grupo_id uuid := gen_random_uuid();
  v_membro_base   record;
  v_item          jsonb;
BEGIN
  SELECT socio_cpf, sessao_id, tipo_boleto, forma_pagamento, data_recebimento 
  INTO v_membro_base
  FROM public.financeiro_dae 
  WHERE grupo_id = p_grupo_id 
  LIMIT 1;

  IF NOT FOUND THEN
    RAISE EXCEPTION 'Grupo não encontrado: %', p_grupo_id;
  END IF;

  UPDATE public.financeiro_dae
  SET status = 'cancelado',
      cancelado_em = now(),
      cancelado_por = auth.uid(),
      cancelamento_obs = 'Correção: Grupo re-emitido devido a edição de valores/competência'
  WHERE grupo_id = p_grupo_id AND status != 'cancelado';

  FOR v_item IN SELECT * FROM jsonb_array_elements(p_items)
  LOOP
    INSERT INTO public.financeiro_dae (
      socio_cpf, sessao_id, tipo_boleto, competencia_ano, competencia_mes,
      valor, forma_pagamento, boleto_pago, data_pagamento_boleto,
      status, registrado_por, data_recebimento, grupo_id
    )
    VALUES (
      v_membro_base.socio_cpf, v_membro_base.sessao_id, v_membro_base.tipo_boleto,
      p_new_year, (v_item->>'mes')::int, (v_item->>'valor')::numeric,
      v_membro_base.forma_pagamento,
      COALESCE((SELECT boleto_pago FROM public.financeiro_dae WHERE grupo_id = p_grupo_id AND competencia_mes = (v_item->>'mes')::int LIMIT 1), false),
      (SELECT data_pagamento_boleto FROM public.financeiro_dae WHERE grupo_id = p_grupo_id AND competencia_mes = (v_item->>'mes')::int LIMIT 1),
      'pago', auth.uid(), v_membro_base.data_recebimento, v_novo_grupo_id
    );
  END LOOP;
END;
$function$;

CREATE OR REPLACE FUNCTION public.get_finance_tab_counts(
  p_search_term text DEFAULT '',
  p_year integer DEFAULT NULL,
  p_ano_base integer DEFAULT 2024
) RETURNS jsonb
LANGUAGE plpgsql STABLE SECURITY DEFINER AS $$
DECLARE
  v_year integer;
  v_required_years integer[];
  v_result jsonb;
  v_todos bigint;
  v_isentos bigint;
  v_liberados bigint;
  v_em_dia bigint;
BEGIN
  v_year := COALESCE(p_year, EXTRACT(YEAR FROM CURRENT_DATE)::integer);
  v_required_years := ARRAY(SELECT generate_series(p_ano_base, v_year));

  SELECT
    COUNT(*),
    COUNT(*) FILTER (WHERE isento = true),
    COUNT(*) FILTER (WHERE liberado_presidente = true),
    COUNT(*) FILTER (
      WHERE isento = false
        AND liberado_presidente = false
        AND anuidades_pagas @> v_required_years
    )
  INTO v_todos, v_isentos, v_liberados, v_em_dia
  FROM v_situacao_financeira_socio
  WHERE (p_search_term = '' OR nome ILIKE '%' || p_search_term || '%'
         OR cpf ILIKE '%' || p_search_term || '%');

  v_result := jsonb_build_object(
    'todos', v_todos,
    'em-dia', v_em_dia,
    'inadimplentes', GREATEST(v_todos - COALESCE(v_em_dia, 0) - COALESCE(v_isentos, 0) - COALESCE(v_liberados, 0), 0),
    'liberados', COALESCE(v_liberados, 0),
    'isentos', COALESCE(v_isentos, 0)
  );

  RETURN v_result;
END;
$$;

-- 3. TABLES
CREATE TABLE public."User" (
    id uuid NOT NULL PRIMARY KEY,
    email text,
    "createdAt" timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    role text DEFAULT 'user'::text,
    acesso_expira_em timestamp with time zone,
    max_socios integer DEFAULT 5
);

CREATE TABLE public.templates (
    id uuid DEFAULT gen_random_uuid() NOT NULL PRIMARY KEY,
    name text,
    document_type text,
    file_path text,
    file_url text,
    file_size bigint,
    content_type text,
    created_at timestamp with time zone DEFAULT now(),
    updated_at timestamp with time zone DEFAULT now(),
    font_configurations text
);

CREATE TABLE public.entidade (
    id uuid DEFAULT gen_random_uuid() NOT NULL PRIMARY KEY,
    nome_entidade text,
    nome_abreviado text,
    endereco text,
    bairro text,
    cidade text,
    uf text,
    cep text,
    fone text,
    celular text,
    cnpj text,
    federacao text,
    confederacao text,
    polo text,
    fundacao text,
    email text,
    comarca text,
    numero text,
    nome_do_presidente text,
    cpf_do_presidente text
);

CREATE TABLE public.localidades (
    id uuid DEFAULT gen_random_uuid() NOT NULL PRIMARY KEY,
    codigo_localidade text,
    nome text
);

CREATE TABLE public.parametros (
    id uuid DEFAULT gen_random_uuid() NOT NULL PRIMARY KEY,
    nr_publicacao text,
    data_publicacao text,
    local_pesca text,
    inicio_pesca1 text,
    final_pesca1 text,
    inicio_pesca2 text,
    final_pesca2 text,
    especies_proibidas text,
    localpesca text
);

CREATE TABLE public.socios (
    id uuid DEFAULT gen_random_uuid() NOT NULL PRIMARY KEY,
    codigo_do_socio text,
    data_de_admissao date,
    codigo_localidade text,
    data_de_nascimento date,
    nome text,
    apelido text,
    pai text,
    mae text,
    estado_civil text,
    nacionalidade text,
    naturalidade text,
    uf_naturalidade text,
    endereco text,
    num text,
    bairro text,
    cidade text,
    uf text,
    cep text,
    telefone text,
    alfabetizado text,
    escolaridade text,
    rg text,
    uf_rg text,
    dt_expedicao_rg date,
    cpf text UNIQUE,
    titulo text,
    zona text,
    secao text,
    num_rgp text,
    rgp_uf text,
    nit text,
    cei text,
    caepf text,
    emissao_rgp date,
    situacao text,
    sexo text,
    email text,
    senhagov_inss text,
    observacoes text,
    tipo_rgp text,
    created_at timestamp with time zone DEFAULT now(),
    updated_at timestamp with time zone DEFAULT now()
);

CREATE TABLE public.fotos (
    cpf text PRIMARY KEY REFERENCES public.socios(cpf),
    foto_url text,
    created_at timestamp with time zone DEFAULT now(),
    updated_at timestamp with time zone DEFAULT now()
);

CREATE TABLE public.foto_upload_tokens (
    token uuid DEFAULT gen_random_uuid() NOT NULL PRIMARY KEY,
    socio_cpf text REFERENCES public.socios(cpf) ON DELETE CASCADE,
    foto_base64 text,
    expires_at timestamp with time zone DEFAULT (now() + '00:10:00'::interval),
    created_at timestamp with time zone DEFAULT now(),
    updated_at timestamp with time zone DEFAULT now()
);

CREATE TABLE public.requerimentos (
    id uuid DEFAULT gen_random_uuid() NOT NULL PRIMARY KEY,
    cod_req text UNIQUE,
    data date,
    cpf text REFERENCES public.socios(cpf) ON DELETE CASCADE
);

CREATE TABLE public.parametros_financeiros (
    id uuid DEFAULT gen_random_uuid() NOT NULL PRIMARY KEY,
    regime_padrao text DEFAULT 'anuidade'::text CHECK (regime_padrao = ANY (ARRAY['anuidade'::text, 'mensalidade'::text])),
    dia_vencimento integer DEFAULT 1 CHECK (dia_vencimento >= 1 AND dia_vencimento <= 28),
    ano_base_cobranca integer DEFAULT 2024,
    valor_anuidade numeric,
    valor_mensalidade numeric,
    valor_inscricao numeric,
    valor_transferencia numeric,
    bloquear_inadimplente boolean DEFAULT true,
    anos_atraso_alerta integer DEFAULT 1,
    cobra_multa boolean DEFAULT false,
    percentual_multa numeric,
    cobra_juros boolean DEFAULT false,
    percentual_juros_mes numeric,
    created_at timestamp with time zone DEFAULT now(),
    updated_at timestamp with time zone DEFAULT now()
);

CREATE TABLE public.tipos_cobranca (
    id uuid DEFAULT gen_random_uuid() NOT NULL PRIMARY KEY,
    categoria text CHECK (categoria = ANY (ARRAY['contribuicao'::text, 'cadastro_governamental'::text])),
    nome text,
    descricao text,
    valor_padrao numeric,
    obrigatoriedade text CHECK (obrigatoriedade = ANY (ARRAY['compulsoria'::text, 'facultativa'::text])),
    ativo boolean DEFAULT true,
    created_at timestamp with time zone DEFAULT now(),
    updated_at timestamp with time zone DEFAULT now()
);

CREATE TABLE public.financeiro_lancamentos (
    id uuid DEFAULT gen_random_uuid() NOT NULL PRIMARY KEY,
    socio_cpf text REFERENCES public.socios(cpf),
    sessao_id uuid DEFAULT gen_random_uuid(),
    tipo text CHECK (tipo = ANY (ARRAY['anuidade'::text, 'mensalidade'::text, 'inicial'::text, 'transferencia'::text, 'contribuicao'::text, 'cadastro_governamental'::text])),
    tipo_cobranca_id uuid REFERENCES public.tipos_cobranca(id),
    competencia_ano integer,
    competencia_mes integer CHECK (competencia_mes >= 1 AND competencia_mes <= 12),
    valor numeric,
    forma_pagamento text CHECK (forma_pagamento = ANY (ARRAY['dinheiro'::text, 'pix'::text, 'transferencia'::text, 'boleto'::text, 'cartao'::text])),
    descricao text,
    status text DEFAULT 'pago'::text CHECK (status = ANY (ARRAY['pago'::text, 'cancelado'::text])),
    cancelado_em timestamp with time zone,
    cancelado_por uuid REFERENCES public."User"(id),
    cancelamento_obs text,
    registrado_por uuid REFERENCES public."User"(id),
    data_pagamento date DEFAULT CURRENT_DATE,
    created_at timestamp with time zone DEFAULT now(),
    updated_at timestamp with time zone DEFAULT now()
);

CREATE TABLE public.financeiro_cobrancas_geradas (
    id uuid DEFAULT gen_random_uuid() NOT NULL PRIMARY KEY,
    tipo_cobranca_id uuid REFERENCES public.tipos_cobranca(id),
    socio_cpf text REFERENCES public.socios(cpf),
    valor numeric,
    data_lancamento date DEFAULT CURRENT_DATE,
    data_vencimento date,
    lancamento_id uuid REFERENCES public.financeiro_lancamentos(id),
    status text DEFAULT 'pendente'::text CHECK (status = ANY (ARRAY['pendente'::text, 'pago'::text, 'cancelado'::text])),
    cancelado_em timestamp with time zone,
    cancelado_por uuid REFERENCES public."User"(id),
    cancelamento_obs text,
    created_at timestamp with time zone DEFAULT now(),
    updated_at timestamp with time zone DEFAULT now()
);

CREATE TABLE public.financeiro_dae (
    id uuid DEFAULT gen_random_uuid() NOT NULL PRIMARY KEY,
    socio_cpf text REFERENCES public.socios(cpf),
    tipo_boleto text CHECK (tipo_boleto = ANY (ARRAY['unitario'::text, 'agrupado'::text, 'anual'::text])),
    competencia_ano integer,
    competencia_mes integer CHECK (competencia_mes >= 1 AND competencia_mes <= 12),
    grupo_id uuid,
    sessao_id uuid,
    valor numeric,
    forma_pagamento text CHECK (forma_pagamento = ANY (ARRAY['dinheiro'::text, 'pix'::text, 'transferencia'::text, 'boleto'::text, 'cartao'::text])),
    boleto_pago boolean DEFAULT false,
    data_pagamento_boleto date,
    status text DEFAULT 'pago'::text CHECK (status = ANY (ARRAY['pago'::text, 'cancelado'::text])),
    registrado_por uuid REFERENCES public."User"(id),
    data_recebimento date DEFAULT CURRENT_DATE,
    created_at timestamp with time zone DEFAULT now(),
    updated_at timestamp with time zone DEFAULT now(),
    cancelado_em timestamp with time zone,
    cancelado_por uuid REFERENCES public."User"(id),
    cancelamento_obs text
);

CREATE TABLE public.financeiro_config_socio (
    cpf text NOT NULL PRIMARY KEY REFERENCES public.socios(cpf),
    regime text CHECK (regime = ANY (ARRAY['anuidade'::text, 'mensalidade'::text])),
    referencia_vencimento text CHECK (referencia_vencimento = ANY (ARRAY['dia_fixo'::text, 'admissao'::text, 'rgp'::text])),
    dia_vencimento integer CHECK (dia_vencimento >= 1 AND dia_vencimento <= 28),
    isento boolean DEFAULT false,
    motivo_isencao text,
    liberado_pelo_presidente boolean DEFAULT false,
    liberacao_observacao text,
    liberacao_data timestamp with time zone,
    liberacao_usuario_id uuid REFERENCES public."User"(id),
    socio_historico boolean DEFAULT false,
    created_at timestamp with time zone DEFAULT now(),
    updated_at timestamp with time zone DEFAULT now()
);

CREATE TABLE public.financeiro_historico_regime (
    id uuid DEFAULT gen_random_uuid() NOT NULL PRIMARY KEY,
    socio_cpf text REFERENCES public.socios(cpf),
    regime text CHECK (regime = ANY (ARRAY['anuidade'::text, 'mensalidade'::text])),
    vigente_desde date,
    vigente_ate date,
    alterado_por uuid REFERENCES public."User"(id),
    observacao text,
    created_at timestamp with time zone DEFAULT now()
);

-- 4. INDEXES
CREATE UNIQUE INDEX financeiro_dae_active_month_idx ON public.financeiro_dae (socio_cpf, competencia_ano, competencia_mes) WHERE (status <> 'cancelado'::text);
CREATE INDEX idx_dae_socio ON public.financeiro_dae (socio_cpf);
CREATE INDEX idx_dae_comp ON public.financeiro_dae (competencia_ano, competencia_mes);
CREATE INDEX idx_dae_grupo ON public.financeiro_dae (grupo_id);
CREATE INDEX idx_dae_sessao ON public.financeiro_dae (sessao_id);

CREATE INDEX idx_fin_lanc_socio ON public.financeiro_lancamentos (socio_cpf);
CREATE INDEX idx_fin_lanc_sessao ON public.financeiro_lancamentos (sessao_id);
CREATE INDEX idx_fin_lanc_tipo ON public.financeiro_lancamentos (tipo);
CREATE INDEX idx_fin_lanc_data ON public.financeiro_lancamentos (data_pagamento);
CREATE INDEX idx_fin_lanc_comp_ano ON public.financeiro_lancamentos (competencia_ano);
CREATE INDEX idx_fin_lanc_status ON public.financeiro_lancamentos (status);
CREATE INDEX idx_fin_lanc_tipo_cobranca ON public.financeiro_lancamentos (tipo_cobranca_id);
CREATE INDEX idx_fin_lanc_socio_tipo_comp ON public.financeiro_lancamentos (socio_cpf, tipo, competencia_ano, competencia_mes);

CREATE UNIQUE INDEX uniq_anuidade_por_ano ON public.financeiro_lancamentos (socio_cpf, competencia_ano) WHERE ((tipo = 'anuidade'::text) AND (status = 'pago'::text));
CREATE UNIQUE INDEX uniq_mensalidade_por_mes ON public.financeiro_lancamentos (socio_cpf, competencia_ano, competencia_mes) WHERE ((tipo = 'mensalidade'::text) AND (status = 'pago'::text));
CREATE UNIQUE INDEX uniq_tipo_cobranca_por_socio ON public.financeiro_lancamentos (socio_cpf, tipo_cobranca_id) WHERE ((status = 'pago'::text) AND (tipo_cobranca_id IS NOT NULL));

CREATE INDEX idx_cobrancas_socio ON public.financeiro_cobrancas_geradas (socio_cpf);
CREATE INDEX idx_cobrancas_tipo ON public.financeiro_cobrancas_geradas (tipo_cobranca_id);
CREATE INDEX idx_cobrancas_status ON public.financeiro_cobrancas_geradas (status);
CREATE UNIQUE INDEX financeiro_cobrancas_geradas_tipo_id_socio_cpf_key ON public.financeiro_cobrancas_geradas (tipo_cobranca_id, socio_cpf);

CREATE INDEX idx_regime_socio ON public.financeiro_historico_regime (socio_cpf);
CREATE INDEX idx_tipos_cobranca_categoria ON public.tipos_cobranca (categoria);
CREATE INDEX idx_tipos_cobranca_ativo ON public.tipos_cobranca (ativo);

-- 5. TRIGGERS
CREATE TRIGGER trigger_auto_generate_cod_req BEFORE INSERT ON public.requerimentos FOR EACH ROW EXECUTE FUNCTION public.auto_generate_cod_req();
CREATE TRIGGER trigger_generate_codigo_localidade BEFORE INSERT ON public.localidades FOR EACH ROW EXECUTE FUNCTION public.generate_next_codigo_localidade();
CREATE TRIGGER tr_check_member_limit BEFORE INSERT ON public.socios FOR EACH ROW EXECUTE FUNCTION public.check_member_limit();

CREATE TRIGGER on_auth_user_created AFTER INSERT ON auth.users FOR EACH ROW EXECUTE FUNCTION handle_new_user();
CREATE TRIGGER on_auth_user_deleted AFTER DELETE ON auth.users FOR EACH ROW EXECUTE FUNCTION handle_delete_user();
CREATE TRIGGER on_auth_user_updated AFTER UPDATE OF email ON auth.users FOR EACH ROW EXECUTE FUNCTION handle_update_user();

-- Trigger de updated_at para tabelas financeiras
CREATE TRIGGER trg_parametros_financeiros_upd
  BEFORE UPDATE ON public.parametros_financeiros
  FOR EACH ROW EXECUTE FUNCTION public.update_updated_at_column();

CREATE TRIGGER trg_tipos_cobranca_upd
  BEFORE UPDATE ON public.tipos_cobranca
  FOR EACH ROW EXECUTE FUNCTION public.update_updated_at_column();

CREATE TRIGGER trg_fin_lancamentos_upd
  BEFORE UPDATE ON public.financeiro_lancamentos
  FOR EACH ROW EXECUTE FUNCTION public.update_updated_at_column();

CREATE TRIGGER trg_fin_dae_upd
  BEFORE UPDATE ON public.financeiro_dae
  FOR EACH ROW EXECUTE FUNCTION public.update_updated_at_column();

CREATE TRIGGER trg_fin_config_socio_upd
  BEFORE UPDATE ON public.financeiro_config_socio
  FOR EACH ROW EXECUTE FUNCTION public.update_updated_at_column();

CREATE TRIGGER trg_cobrancas_geradas_upd
  BEFORE UPDATE ON public.financeiro_cobrancas_geradas
  FOR EACH ROW EXECUTE FUNCTION public.update_updated_at_column();

CREATE TRIGGER trg_fotos_upd
  BEFORE UPDATE ON public.fotos
  FOR EACH ROW EXECUTE FUNCTION public.update_updated_at_column();

CREATE TRIGGER trg_socios_upd
  BEFORE UPDATE ON public.socios
  FOR EACH ROW EXECUTE FUNCTION public.update_updated_at_column();

-- 6. RLS POLICIES
ALTER TABLE public."User" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.templates ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.entidade ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.localidades ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.parametros ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.socios ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.fotos ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.requerimentos ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.parametros_financeiros ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.tipos_cobranca ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.financeiro_lancamentos ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.financeiro_cobrancas_geradas ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.financeiro_dae ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.financeiro_config_socio ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.financeiro_historico_regime ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.foto_upload_tokens ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Allow all for authenticated users" ON public.templates FOR ALL TO authenticated USING (auth.uid() IS NOT NULL);
CREATE POLICY "Allow all for authenticated users" ON public.entidade FOR ALL TO authenticated USING (auth.uid() IS NOT NULL);
CREATE POLICY "Allow all for authenticated users" ON public.localidades FOR ALL TO authenticated USING (auth.uid() IS NOT NULL);
CREATE POLICY "Allow all for authenticated users" ON public.parametros FOR ALL TO authenticated USING (auth.uid() IS NOT NULL);
CREATE POLICY "Allow all for authenticated users" ON public.socios FOR ALL TO authenticated USING (auth.uid() IS NOT NULL);
CREATE POLICY "Allow all for authenticated users_fotos" ON public.fotos FOR ALL TO authenticated USING (auth.uid() IS NOT NULL);
CREATE POLICY "Allow all for authenticated users" ON public.requerimentos FOR ALL TO authenticated USING (auth.uid() IS NOT NULL);
CREATE POLICY "Allow all for authenticated users" ON public.parametros_financeiros FOR ALL TO authenticated USING (auth.uid() IS NOT NULL) WITH CHECK (auth.uid() IS NOT NULL);
CREATE POLICY "Allow all for authenticated users" ON public.tipos_cobranca FOR ALL TO authenticated USING (auth.uid() IS NOT NULL) WITH CHECK (auth.uid() IS NOT NULL);
CREATE POLICY "Allow all for authenticated users" ON public.financeiro_lancamentos FOR ALL TO authenticated USING (auth.uid() IS NOT NULL) WITH CHECK (auth.uid() IS NOT NULL);
CREATE POLICY "Allow all for authenticated users" ON public.financeiro_cobrancas_geradas FOR ALL TO authenticated USING (auth.uid() IS NOT NULL) WITH CHECK (auth.uid() IS NOT NULL);
CREATE POLICY "Allow all for authenticated users" ON public.financeiro_dae FOR ALL TO authenticated USING (auth.uid() IS NOT NULL) WITH CHECK (auth.uid() IS NOT NULL);
CREATE POLICY "Allow all for authenticated users" ON public.financeiro_config_socio FOR ALL TO authenticated USING (auth.uid() IS NOT NULL) WITH CHECK (auth.uid() IS NOT NULL);
CREATE POLICY "Allow all for authenticated users" ON public.financeiro_historico_regime FOR ALL TO authenticated USING (auth.uid() IS NOT NULL) WITH CHECK (auth.uid() IS NOT NULL);
CREATE POLICY "Public insert for valid tokens" ON public.foto_upload_tokens FOR UPDATE TO public USING (expires_at > now());
CREATE POLICY "Full access for authenticated workers" ON public.foto_upload_tokens FOR ALL TO authenticated USING (true);

CREATE POLICY "Service role can manage users" ON public."User" FOR ALL TO service_role USING (true);
CREATE POLICY "Allow user to read own User data" ON public."User" FOR SELECT TO authenticated USING (auth.uid() = id);

-- 7. STORAGE BUCKETS & POLICIES
INSERT INTO storage.buckets (id, name, public, file_size_limit) VALUES ('fotos', 'fotos', true, NULL) ON CONFLICT (id) DO NOTHING;
INSERT INTO storage.buckets (id, name, public, file_size_limit) VALUES ('documentos', 'documentos', true, 5242880) ON CONFLICT (id) DO NOTHING;

CREATE POLICY "Public Access" ON storage.objects FOR SELECT TO public USING (bucket_id = 'fotos');
CREATE POLICY "Acesso total para usuários autenticados_fotos" ON storage.objects FOR ALL TO authenticated USING (bucket_id = 'fotos');
CREATE POLICY "Acesso total para usuários autenticados_documentos" ON storage.objects FOR ALL TO authenticated USING (bucket_id = 'documentos');

-- 8. VIEWS
CREATE OR REPLACE VIEW public.v_debitos_socio WITH (security_invoker = on) AS
 WITH anos AS (
         SELECT generate_series(( SELECT parametros_financeiros.ano_base_cobranca FROM public.parametros_financeiros LIMIT 1), (EXTRACT(year FROM CURRENT_DATE))::integer) AS ano
        )
 SELECT s.cpf, s.nome, a.ano,
    (NOT (EXISTS ( SELECT 1 FROM public.financeiro_lancamentos fl WHERE ((fl.socio_cpf = s.cpf) AND (fl.tipo = 'anuidade'::text) AND (fl.competencia_ano = a.ano) AND (fl.status = 'pago'::text))))) AS anuidade_pendente,
    COALESCE(cfg.isento, false) AS isento,
    COALESCE(cfg.liberado_pelo_presidente, false) AS liberado
   FROM (((public.socios s CROSS JOIN anos a) LEFT JOIN public.financeiro_config_socio cfg ON ((cfg.cpf = s.cpf))) CROSS JOIN public.parametros_financeiros pf)
  WHERE ((COALESCE(cfg.regime, pf.regime_padrao) = 'anuidade'::text) AND (a.ano >= ( SELECT parametros_financeiros.ano_base_cobranca FROM public.parametros_financeiros LIMIT 1)));

CREATE OR REPLACE VIEW public.v_situacao_financeira_socio WITH (security_invoker = on) AS
 SELECT s.cpf, s.nome, s.situacao AS situacao_associativa,
    COALESCE(cfg.regime, pf.regime_padrao) AS regime,
    COALESCE(cfg.isento, false) AS isento,
    COALESCE(cfg.liberado_pelo_presidente, false) AS liberado_presidente,
    array_agg(fl.competencia_ano ORDER BY fl.competencia_ano) FILTER (WHERE ((fl.tipo = 'anuidade'::text) AND (fl.status = 'pago'::text))) AS anuidades_pagas,
    max(fl.data_pagamento) AS ultimo_pagamento
   FROM (((public.socios s CROSS JOIN public.parametros_financeiros pf) LEFT JOIN public.financeiro_config_socio cfg ON ((cfg.cpf = s.cpf))) LEFT JOIN public.financeiro_lancamentos fl ON ((fl.socio_cpf = s.cpf)))
  GROUP BY s.cpf, s.nome, s.situacao, cfg.regime, pf.regime_padrao, cfg.isento, cfg.liberado_pelo_presidente;
