-- SIGESS Database Schema Dump (Schema-only)
-- Generated by Antigravity using Supabase MCP

-- 1. EXTENSIONS
CREATE EXTENSION IF NOT EXISTS "uuid-ossp" WITH SCHEMA "extensions";
CREATE EXTENSION IF NOT EXISTS "pgcrypto" WITH SCHEMA "extensions";

-- 2. FUNCTIONS
CREATE OR REPLACE FUNCTION public.update_updated_at_column()
 RETURNS trigger
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public, pg_temp'
AS $function$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$function$;

CREATE OR REPLACE FUNCTION public.get_next_cod_req_inss()
 RETURNS text
 LANGUAGE plpgsql
AS $function$
DECLARE
    next_code INTEGER;
    formatted_code TEXT;
BEGIN
    LOCK TABLE requerimentos IN EXCLUSIVE MODE;
    
    SELECT COALESCE(
        MAX(CAST(cod_req_inss AS INTEGER)), 
        0
    ) + 1 
    INTO next_code
    FROM requerimentos 
    WHERE cod_req_inss ~ '^[0-9]+$';
    
    formatted_code := LPAD(next_code::text, 6, '0');
    
    RETURN formatted_code;
END;
$function$;

CREATE OR REPLACE FUNCTION public.auto_generate_cod_req_inss()
 RETURNS trigger
 LANGUAGE plpgsql
AS $function$
BEGIN
    IF NEW.cod_req_inss IS NULL OR NEW.cod_req_inss = '' THEN
        NEW.cod_req_inss := get_next_cod_req_inss();
    END IF;
    
    RETURN NEW;
END;
$function$;

-- 3. TABLES
CREATE TABLE public."User" (
    id uuid NOT NULL PRIMARY KEY,
    email text,
    "createdAt" timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    role text DEFAULT 'user'::text
);

CREATE TABLE public.templates (
    id uuid DEFAULT gen_random_uuid() NOT NULL PRIMARY KEY,
    name text,
    document_type text,
    file_path text,
    file_url text,
    file_size bigint,
    content_type text,
    created_at timestamp with time zone DEFAULT now(),
    updated_at timestamp with time zone DEFAULT now(),
    font_configurations text
);

CREATE TABLE public.entidade (
    id uuid DEFAULT gen_random_uuid() NOT NULL PRIMARY KEY,
    nome_entidade text,
    nome_abreviado text,
    endereco text,
    bairro text,
    cidade text,
    uf text,
    cep text,
    fone text,
    celular text,
    cnpj text,
    federacao text,
    confederacao text,
    polo text,
    fundacao text,
    email text,
    comarca text,
    numero text
);

CREATE TABLE public.localidades (
    id uuid DEFAULT gen_random_uuid() NOT NULL PRIMARY KEY,
    codigo_localidade text,
    nome text
);

CREATE TABLE public.parametros (
    id uuid DEFAULT gen_random_uuid() NOT NULL PRIMARY KEY,
    nr_publicacao text,
    data_publicacao text,
    local_pesca text,
    inicio_pesca1 text,
    final_pesca1 text,
    inicio_pesca2 text,
    final_pesca2 text,
    especies_proibidas text,
    localpesca text
);

CREATE TABLE public.socios (
    id uuid DEFAULT gen_random_uuid() NOT NULL PRIMARY KEY,
    codigo_do_socio text,
    data_de_admissao date,
    codigo_localidade text,
    data_de_nascimento date,
    nome text,
    apelido text,
    pai text,
    mae text,
    estado_civil text,
    nacionalidade text,
    naturalidade text,
    uf_naturalidade text,
    endereco text,
    num text,
    bairro text,
    cidade text,
    uf text,
    cep text,
    telefone text,
    alfabetizado text,
    escolaridade text,
    rg text,
    ssp text,
    dt_expedicao_rg date,
    cpf text UNIQUE,
    titulo text,
    zona text,
    secao text,
    emb_rgp text,
    rgp_uf text,
    nit text,
    cei text,
    caepf text,
    emissao_rgp date,
    situacao text,
    sexo text,
    email text,
    senhagov_inss text,
    observacoes text
);

CREATE TABLE public.fotos (
    cpf text PRIMARY KEY REFERENCES public.socios(cpf),
    foto_url text
);

CREATE TABLE public.requerimentos (
    id uuid DEFAULT gen_random_uuid() NOT NULL PRIMARY KEY,
    cod_req_inss text UNIQUE,
    data date,
    codigo_do_socio text,
    nome text,
    dtnasc date,
    mae text,
    rg text,
    cpf text,
    nit text,
    pis text,
    cei text,
    endereco text,
    num text,
    bairro text,
    cidade text,
    uf text,
    cep text,
    telefone text,
    nrpub text,
    dtpub date,
    area text,
    inicio1 date,
    fim1 text,
    inicio2 text,
    fim2 text,
    especie_proibidas text,
    emb_rgp text,
	rgp_uf text,
	situacao_mpa text
);

-- 4. TRIGGERS
CREATE TRIGGER trigger_auto_generate_cod_req_inss
BEFORE INSERT ON public.requerimentos
FOR EACH ROW
EXECUTE FUNCTION public.auto_generate_cod_req_inss();

-- 5. RLS POLICIES
ALTER TABLE public."User" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.templates ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.entidade ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.localidades ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.parametros ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.socios ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.fotos ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.requerimentos ENABLE ROW LEVEL SECURITY;

-- Policies for public access (examples based on previous MCP outputs)
CREATE POLICY "Allow all for authenticated users" ON public.templates FOR ALL TO authenticated USING (auth.uid() IS NOT NULL);
CREATE POLICY "Allow all for authenticated users" ON public.entidade FOR ALL TO authenticated USING (auth.uid() IS NOT NULL);
CREATE POLICY "Allow all for authenticated users" ON public.localidades FOR ALL TO authenticated USING (auth.uid() IS NOT NULL);
CREATE POLICY "Allow all for authenticated users" ON public.parametros FOR ALL TO authenticated USING (auth.uid() IS NOT NULL);
CREATE POLICY "Allow all for authenticated users" ON public.socios FOR ALL TO authenticated USING (auth.uid() IS NOT NULL);
CREATE POLICY "Allow all for authenticated users_fotos" ON public.fotos FOR ALL TO authenticated USING (auth.uid() IS NOT NULL);
CREATE POLICY "Allow all for authenticated users" ON public.requerimentos FOR ALL TO authenticated USING (auth.uid() IS NOT NULL);

-- Service role can manage users
CREATE POLICY "Service role can manage users" ON public."User" FOR ALL TO service_role USING (true);

-- 6. STORAGE BUCKETS
-- Note: Requires storage schema permissions. If this fails, create buckets manually in Dashboard.
INSERT INTO storage.buckets (id, name, public, file_size_limit) 
VALUES ('fotos', 'fotos', true, NULL)
ON CONFLICT (id) DO NOTHING;

INSERT INTO storage.buckets (id, name, public, file_size_limit) 
VALUES ('documents', 'documents', true, 5242880)
ON CONFLICT (id) DO NOTHING;

-- 7. STORAGE POLICIES
-- fotos bucket policies
CREATE POLICY "Public Access" ON storage.objects FOR SELECT TO public USING (bucket_id = 'fotos');
CREATE POLICY "Authenticated users can upload" ON storage.objects FOR INSERT TO public WITH CHECK (bucket_id = 'fotos');
CREATE POLICY "Authenticated users can update" ON storage.objects FOR UPDATE TO public USING (bucket_id = 'fotos');
CREATE POLICY "Authenticated users can delete" ON storage.objects FOR DELETE TO public USING (bucket_id = 'fotos');

CREATE POLICY "Acesso total para usuários autenticados 1m4ctr_0" ON storage.objects FOR SELECT TO authenticated USING (bucket_id = 'fotos');
CREATE POLICY "Acesso total para usuários autenticados 1m4ctr_1" ON storage.objects FOR INSERT TO authenticated WITH CHECK (bucket_id = 'fotos');
CREATE POLICY "Acesso total para usuários autenticados 1m4ctr_2" ON storage.objects FOR UPDATE TO authenticated USING (bucket_id = 'fotos');
CREATE POLICY "Acesso total para usuários autenticados 1m4ctr_3" ON storage.objects FOR DELETE TO authenticated USING (bucket_id = 'fotos');

-- documents bucket policies
CREATE POLICY "Acesso total para usuários autenticados flreew_0" ON storage.objects FOR UPDATE TO authenticated USING (bucket_id = 'documents');
CREATE POLICY "Acesso total para usuários autenticados flreew_1" ON storage.objects FOR DELETE TO authenticated USING (bucket_id = 'documents');
CREATE POLICY "Acesso total para usuários autenticados flreew_2" ON storage.objects FOR INSERT TO authenticated WITH CHECK (bucket_id = 'documents');
CREATE POLICY "Acesso total para usuários autenticados flreew_3" ON storage.objects FOR SELECT TO authenticated USING (bucket_id = 'documents');
