-- SIGESS Database Schema Dump (Schema-only)
-- Generated by Antigravity using Supabase MCP

-- 1. EXTENSIONS
CREATE EXTENSION IF NOT EXISTS "uuid-ossp" WITH SCHEMA "extensions";
CREATE EXTENSION IF NOT EXISTS "pgcrypto" WITH SCHEMA "extensions";

-- 2. FUNCTIONS
CREATE OR REPLACE FUNCTION public.update_updated_at_column()
 RETURNS trigger
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public, pg_temp'
AS $function$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$function$;

CREATE OR REPLACE FUNCTION public.check_member_limit()
 RETURNS trigger
 LANGUAGE plpgsql
 SECURITY DEFINER
AS $function$
DECLARE
    v_max_socios INTEGER;
    v_current_count INTEGER;
BEGIN
    -- Obter o limite do usuário autenticado atual
    SELECT max_socios INTO v_max_socios
    FROM public."User"
    WHERE id = auth.uid();

    -- Se não houver limite definido, permite por padrão
    IF v_max_socios IS NULL THEN
        RETURN NEW;
    END IF;

    -- Contar membros atuais
    SELECT count(*) INTO v_current_count FROM public.socios;

    -- Verificar se o limite foi atingido
    IF v_current_count >= v_max_socios THEN
        RAISE EXCEPTION 'limite_cadastros: Limite de % sócios atingido.', v_max_socios;
    END IF;

    RETURN NEW;
END;
$function$;

CREATE OR REPLACE FUNCTION public.generate_next_codigo_localidade()
 RETURNS trigger
 LANGUAGE plpgsql
AS $function$
DECLARE
  max_code_val integer;
  next_code text;
BEGIN
  -- Find the maximum current code, treating it as integer
  -- regexp_replace removes any non-numeric characters just in case
  SELECT COALESCE(MAX(NULLIF(regexp_replace(codigo_localidade, '\D', '', 'g'), '')::integer), 0)
  INTO max_code_val
  FROM public.localidades;

  -- Increment and pad to 3 digits (e.g., 1 -> '001', 42 -> '042')
  next_code := LPAD((max_code_val + 1)::text, 3, '0');

  -- Assign to the new record only if it's currently null or empty
  IF NEW.codigo_localidade IS NULL OR NEW.codigo_localidade = '' THEN
    NEW.codigo_localidade := next_code;
  END IF;

  RETURN NEW;
END;
$function$;

CREATE OR REPLACE FUNCTION public.handle_delete_user()
 RETURNS trigger
 LANGUAGE plpgsql
 SECURITY DEFINER
AS $function$
BEGIN
  DELETE FROM public."User" WHERE id = OLD.id;
  RETURN OLD;
END;
$function$;

CREATE OR REPLACE FUNCTION public.handle_new_user()
 RETURNS trigger
 LANGUAGE plpgsql
 SECURITY DEFINER
AS $function$
BEGIN
  INSERT INTO public."User" (id, email, role)
  VALUES (NEW.id, NEW.email, 'user');
  RETURN NEW;
END;
$function$;

CREATE OR REPLACE FUNCTION public.handle_update_user()
 RETURNS trigger
 LANGUAGE plpgsql
 SECURITY DEFINER
AS $function$
BEGIN
  UPDATE public."User"
  SET email = NEW.email
  WHERE id = NEW.id;
  RETURN NEW;
END;
$function$;

CREATE OR REPLACE FUNCTION public.get_next_cod_req()
 RETURNS text
 LANGUAGE plpgsql
AS $function$
DECLARE
    next_code INTEGER;
    formatted_code TEXT;
BEGIN
    LOCK TABLE requerimentos IN EXCLUSIVE MODE;
    
    SELECT COALESCE(
        MAX(CAST(cod_req AS INTEGER)), 
        0
    ) + 1 
    INTO next_code
    FROM requerimentos 
    WHERE cod_req ~ '^[0-9]+$';
    
    formatted_code := LPAD(next_code::text, 6, '0');
    
    RETURN formatted_code;
END;
$function$;

CREATE OR REPLACE FUNCTION public.auto_generate_cod_req()
 RETURNS trigger
 LANGUAGE plpgsql
AS $function$
BEGIN
    IF NEW.cod_req IS NULL OR NEW.cod_req = '' THEN
        NEW.cod_req := get_next_cod_req();
    END IF;
    
    RETURN NEW;
END;
$function$;

-- 3. TABLES
CREATE TABLE public."User" (
    id uuid NOT NULL PRIMARY KEY,
    email text,
    "createdAt" timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    role text DEFAULT 'user'::text,
    acesso_expira_em timestamp with time zone,
    max_socios integer DEFAULT 5
);

CREATE TABLE public.templates (
    id uuid DEFAULT gen_random_uuid() NOT NULL PRIMARY KEY,
    name text,
    document_type text,
    file_path text,
    file_url text,
    file_size bigint,
    content_type text,
    created_at timestamp with time zone DEFAULT now(),
    updated_at timestamp with time zone DEFAULT now(),
    font_configurations text
);

CREATE TABLE public.entidade (
    id uuid DEFAULT gen_random_uuid() NOT NULL PRIMARY KEY,
    nome_entidade text,
    nome_abreviado text,
    endereco text,
    bairro text,
    cidade text,
    uf text,
    cep text,
    fone text,
    celular text,
    cnpj text,
    federacao text,
    confederacao text,
    polo text,
    fundacao text,
    email text,
    comarca text,
    numero text,
    nome_do_presidente text,
    cpf_do_presidente text
);

CREATE TABLE public.localidades (
    id uuid DEFAULT gen_random_uuid() NOT NULL PRIMARY KEY,
    codigo_localidade text,
    nome text
);

CREATE TABLE public.parametros (
    id uuid DEFAULT gen_random_uuid() NOT NULL PRIMARY KEY,
    nr_publicacao text,
    data_publicacao text,
    local_pesca text,
    inicio_pesca1 text,
    final_pesca1 text,
    inicio_pesca2 text,
    final_pesca2 text,
    especies_proibidas text,
    localpesca text
);

CREATE TABLE public.socios (
    id uuid DEFAULT gen_random_uuid() NOT NULL PRIMARY KEY,
    codigo_do_socio text,
    data_de_admissao date,
    codigo_localidade text,
    data_de_nascimento date,
    nome text,
    apelido text,
    pai text,
    mae text,
    estado_civil text,
    nacionalidade text,
    naturalidade text,
    uf_naturalidade text,
    endereco text,
    num text,
    bairro text,
    cidade text,
    uf text,
    cep text,
    telefone text,
    alfabetizado text,
    escolaridade text,
    rg text,
    ssp text,
    dt_expedicao_rg date,
    cpf text UNIQUE,
    titulo text,
    zona text,
    secao text,
    num_rgp text,
    rgp_uf text,
    nit text,
    cei text,
    caepf text,
    emissao_rgp date,
    situacao text,
    sexo text,
    email text,
    senhagov_inss text,
    observacoes text,
    tipo_rgp text
);

CREATE TABLE public.fotos (
    cpf text PRIMARY KEY REFERENCES public.socios(cpf),
    foto_url text
);

CREATE TABLE public.requerimentos (
    id uuid DEFAULT gen_random_uuid() NOT NULL PRIMARY KEY,
    cod_req text UNIQUE,
    data date,
    cpf text REFERENCES public.socios(cpf) ON DELETE CASCADE
);

-- 4. TRIGGERS
CREATE TRIGGER trigger_auto_generate_cod_req
BEFORE INSERT ON public.requerimentos
FOR EACH ROW
EXECUTE FUNCTION public.auto_generate_cod_req();

CREATE TRIGGER trigger_generate_codigo_localidade
BEFORE INSERT ON public.localidades
FOR EACH ROW
EXECUTE FUNCTION public.generate_next_codigo_localidade();

CREATE TRIGGER tr_check_member_limit
BEFORE INSERT ON public.socios
FOR EACH ROW
EXECUTE FUNCTION public.check_member_limit();

-- 5. AUTH TRIGGERS (Special schema)
DROP TRIGGER IF EXISTS on_auth_user_created ON auth.users;
CREATE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW EXECUTE FUNCTION handle_new_user();

DROP TRIGGER IF EXISTS on_auth_user_deleted ON auth.users;
CREATE TRIGGER on_auth_user_deleted
  AFTER DELETE ON auth.users
  FOR EACH ROW EXECUTE FUNCTION handle_delete_user();

DROP TRIGGER IF EXISTS on_auth_user_updated ON auth.users;
CREATE TRIGGER on_auth_user_updated
  AFTER UPDATE OF email ON auth.users
  FOR EACH ROW EXECUTE FUNCTION handle_update_user();

-- 6. RLS POLICIES
ALTER TABLE public."User" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.templates ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.entidade ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.localidades ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.parametros ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.socios ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.fotos ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.requerimentos ENABLE ROW LEVEL SECURITY;

-- Policies for public access (examples based on previous MCP outputs)
CREATE POLICY "Allow all for authenticated users" ON public.templates FOR ALL TO authenticated USING (auth.uid() IS NOT NULL);
CREATE POLICY "Allow all for authenticated users" ON public.entidade FOR ALL TO authenticated USING (auth.uid() IS NOT NULL);
CREATE POLICY "Allow all for authenticated users" ON public.localidades FOR ALL TO authenticated USING (auth.uid() IS NOT NULL);
CREATE POLICY "Allow all for authenticated users" ON public.parametros FOR ALL TO authenticated USING (auth.uid() IS NOT NULL);
CREATE POLICY "Allow all for authenticated users" ON public.socios FOR ALL TO authenticated USING (auth.uid() IS NOT NULL);
CREATE POLICY "Allow all for authenticated users_fotos" ON public.fotos FOR ALL TO authenticated USING (auth.uid() IS NOT NULL);
CREATE POLICY "Allow all for authenticated users" ON public.requerimentos FOR ALL TO authenticated USING (auth.uid() IS NOT NULL);

-- Service role can manage users
CREATE POLICY "Service role can manage users" ON public."User" FOR ALL TO service_role USING (true);
CREATE POLICY "Allow user to read own User data" ON public."User" FOR SELECT TO authenticated USING (auth.uid() = id);

-- 6. STORAGE BUCKETS
-- Note: Requires storage schema permissions. If this fails, create buckets manually in Dashboard.
INSERT INTO storage.buckets (id, name, public, file_size_limit) 
VALUES ('fotos', 'fotos', true, NULL)
ON CONFLICT (id) DO NOTHING;

INSERT INTO storage.buckets (id, name, public, file_size_limit) 
VALUES ('documentos', 'documentos', true, 5242880)
ON CONFLICT (id) DO NOTHING;

-- 7. STORAGE POLICIES
-- fotos bucket policies
CREATE POLICY "Public Access" ON storage.objects FOR SELECT TO public USING (bucket_id = 'fotos');
CREATE POLICY "Authenticated users can upload" ON storage.objects FOR INSERT TO public WITH CHECK (bucket_id = 'fotos');
CREATE POLICY "Authenticated users can update" ON storage.objects FOR UPDATE TO public USING (bucket_id = 'fotos');
CREATE POLICY "Authenticated users can delete" ON storage.objects FOR DELETE TO public USING (bucket_id = 'fotos');

CREATE POLICY "Acesso total para usuários autenticados 1m4ctr_0" ON storage.objects FOR SELECT TO authenticated USING (bucket_id = 'fotos');
CREATE POLICY "Acesso total para usuários autenticados 1m4ctr_1" ON storage.objects FOR INSERT TO authenticated WITH CHECK (bucket_id = 'fotos');
CREATE POLICY "Acesso total para usuários autenticados 1m4ctr_2" ON storage.objects FOR UPDATE TO authenticated USING (bucket_id = 'fotos');
CREATE POLICY "Acesso total para usuários autenticados 1m4ctr_3" ON storage.objects FOR DELETE TO authenticated USING (bucket_id = 'fotos');

-- documentos bucket policies
CREATE POLICY "Acesso total para usuários autenticados flreew_0" ON storage.objects FOR UPDATE TO authenticated USING (bucket_id = 'documentos');
CREATE POLICY "Acesso total para usuários autenticados flreew_1" ON storage.objects FOR DELETE TO authenticated USING (bucket_id = 'documentos');
CREATE POLICY "Acesso total para usuários autenticados flreew_2" ON storage.objects FOR INSERT TO authenticated WITH CHECK (bucket_id = 'documentos');
CREATE POLICY "Acesso total para usuários autenticados flreew_3" ON storage.objects FOR SELECT TO authenticated USING (bucket_id = 'documentos');

-- 8. TABELAS DO MÓDULO FINANCEIRO
CREATE TABLE public.parametros_financeiros (
    id uuid DEFAULT gen_random_uuid() NOT NULL PRIMARY KEY,
    regime_padrao text DEFAULT 'anuidade'::text CHECK (regime_padrao = ANY (ARRAY['anuidade'::text, 'mensalidade'::text])),
    dia_vencimento integer DEFAULT 1 CHECK (dia_vencimento >= 1 AND dia_vencimento <= 28),
    ano_base_cobranca integer DEFAULT 2024,
    valor_anuidade numeric,
    valor_mensalidade numeric,
    valor_inscricao numeric,
    valor_transferencia numeric,
    bloquear_inadimplente boolean DEFAULT true,
    anos_atraso_alerta integer DEFAULT 1,
    cobra_multa boolean DEFAULT false,
    percentual_multa numeric,
    cobra_juros boolean DEFAULT false,
    percentual_juros_mes numeric,
    created_at timestamp with time zone DEFAULT now(),
    updated_at timestamp with time zone DEFAULT now()
);

CREATE TABLE public.tipos_cobranca (
    id uuid DEFAULT gen_random_uuid() NOT NULL PRIMARY KEY,
    categoria text CHECK (categoria = ANY (ARRAY['contribuicao'::text, 'cadastro_governamental'::text])),
    nome text,
    descricao text,
    valor_padrao numeric,
    obrigatoriedade text CHECK (obrigatoriedade = ANY (ARRAY['compulsoria'::text, 'facultativa'::text])),
    ativo boolean DEFAULT true,
    created_at timestamp with time zone DEFAULT now(),
    updated_at timestamp with time zone DEFAULT now()
);

CREATE TABLE public.financeiro_lancamentos (
    id uuid DEFAULT gen_random_uuid() NOT NULL PRIMARY KEY,
    socio_cpf text REFERENCES public.socios(cpf),
    sessao_id uuid DEFAULT gen_random_uuid(),
    tipo text CHECK (tipo = ANY (ARRAY['anuidade'::text, 'mensalidade'::text, 'inscricao'::text, 'transferencia'::text, 'contribuicao'::text, 'cadastro_governamental'::text])),
    tipo_cobranca_id uuid REFERENCES public.tipos_cobranca(id),
    competencia_ano integer,
    competencia_mes integer CHECK (competencia_mes >= 1 AND competencia_mes <= 12),
    valor numeric,
    forma_pagamento text CHECK (forma_pagamento = ANY (ARRAY['dinheiro'::text, 'pix'::text, 'transferencia'::text, 'boleto'::text, 'cartao'::text])),
    descricao text,
    status text DEFAULT 'pago'::text CHECK (status = ANY (ARRAY['pago'::text, 'cancelado'::text])),
    cancelado_em timestamp with time zone,
    cancelado_por uuid REFERENCES public."User"(id),
    cancelamento_obs text,
    registrado_por uuid REFERENCES public."User"(id),
    data_pagamento date DEFAULT CURRENT_DATE,
    created_at timestamp with time zone DEFAULT now(),
    updated_at timestamp with time zone DEFAULT now()
);

CREATE TABLE public.financeiro_cobrancas_geradas (
    id uuid DEFAULT gen_random_uuid() NOT NULL PRIMARY KEY,
    tipo_cobranca_id uuid REFERENCES public.tipos_cobranca(id),
    socio_cpf text REFERENCES public.socios(cpf),
    valor numeric,
    data_lancamento date DEFAULT CURRENT_DATE,
    data_vencimento date,
    lancamento_id uuid REFERENCES public.financeiro_lancamentos(id),
    status text DEFAULT 'pendente'::text CHECK (status = ANY (ARRAY['pendente'::text, 'pago'::text, 'cancelado'::text])),
    cancelado_em timestamp with time zone,
    cancelado_por uuid REFERENCES public."User"(id),
    cancelamento_obs text,
    created_at timestamp with time zone DEFAULT now(),
    updated_at timestamp with time zone DEFAULT now()
);

CREATE TABLE public.financeiro_dae (
    id uuid DEFAULT gen_random_uuid() NOT NULL PRIMARY KEY,
    socio_cpf text REFERENCES public.socios(cpf),
    tipo_boleto text CHECK (tipo_boleto = ANY (ARRAY['unitario'::text, 'agrupado'::text, 'anual'::text])),
    competencia_ano integer,
    competencia_mes integer CHECK (competencia_mes >= 1 AND competencia_mes <= 12),
    grupo_id uuid,
    sessao_id uuid,
    valor numeric,
    forma_pagamento text CHECK (forma_pagamento = ANY (ARRAY['dinheiro'::text, 'pix'::text, 'transferencia'::text, 'boleto'::text, 'cartao'::text])),
    boleto_pago boolean DEFAULT false,
    data_pagamento_boleto date,
    status text DEFAULT 'pago'::text CHECK (status = ANY (ARRAY['pago'::text, 'cancelado'::text])),
    registrado_por uuid REFERENCES public."User"(id),
    data_recebimento date DEFAULT CURRENT_DATE,
    created_at timestamp with time zone DEFAULT now(),
    updated_at timestamp with time zone DEFAULT now()
);

CREATE TABLE public.financeiro_config_socio (
    cpf text NOT NULL PRIMARY KEY REFERENCES public.socios(cpf),
    regime text CHECK (regime = ANY (ARRAY['anuidade'::text, 'mensalidade'::text])),
    referencia_vencimento text CHECK (referencia_vencimento = ANY (ARRAY['dia_fixo'::text, 'admissao'::text, 'rgp'::text])),
    dia_vencimento integer CHECK (dia_vencimento >= 1 AND dia_vencimento <= 28),
    isento boolean DEFAULT false,
    motivo_isencao text,
    liberado_pelo_presidente boolean DEFAULT false,
    liberacao_observacao text,
    liberacao_data timestamp with time zone,
    liberacao_usuario_id uuid REFERENCES public."User"(id),
    created_at timestamp with time zone DEFAULT now(),
    updated_at timestamp with time zone DEFAULT now()
);

CREATE TABLE public.financeiro_historico_regime (
    id uuid DEFAULT gen_random_uuid() NOT NULL PRIMARY KEY,
    socio_cpf text REFERENCES public.socios(cpf),
    regime text CHECK (regime = ANY (ARRAY['anuidade'::text, 'mensalidade'::text])),
    vigente_desde date,
    vigente_ate date,
    alterado_por uuid REFERENCES public."User"(id),
    observacao text,
    created_at timestamp with time zone DEFAULT now()
);

-- 9. RLS DO MÓDULO FINANCEIRO
ALTER TABLE public.parametros_financeiros ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.tipos_cobranca ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.financeiro_lancamentos ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.financeiro_cobrancas_geradas ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.financeiro_dae ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.financeiro_config_socio ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.financeiro_historico_regime ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Allow all for authenticated users" ON public.parametros_financeiros FOR ALL TO authenticated USING (auth.uid() IS NOT NULL) WITH CHECK (auth.uid() IS NOT NULL);
CREATE POLICY "Allow all for authenticated users" ON public.tipos_cobranca FOR ALL TO authenticated USING (auth.uid() IS NOT NULL) WITH CHECK (auth.uid() IS NOT NULL);
CREATE POLICY "Allow all for authenticated users" ON public.financeiro_lancamentos FOR ALL TO authenticated USING (auth.uid() IS NOT NULL) WITH CHECK (auth.uid() IS NOT NULL);
CREATE POLICY "Allow all for authenticated users" ON public.financeiro_cobrancas_geradas FOR ALL TO authenticated USING (auth.uid() IS NOT NULL) WITH CHECK (auth.uid() IS NOT NULL);
CREATE POLICY "Allow all for authenticated users" ON public.financeiro_dae FOR ALL TO authenticated USING (auth.uid() IS NOT NULL) WITH CHECK (auth.uid() IS NOT NULL);
CREATE POLICY "Allow all for authenticated users" ON public.financeiro_config_socio FOR ALL TO authenticated USING (auth.uid() IS NOT NULL) WITH CHECK (auth.uid() IS NOT NULL);
CREATE POLICY "Allow all for authenticated users" ON public.financeiro_historico_regime FOR ALL TO authenticated USING (auth.uid() IS NOT NULL) WITH CHECK (auth.uid() IS NOT NULL);

-- 10. VIEWS FINANCEIRAS

CREATE OR REPLACE VIEW public.v_debitos_socio WITH (security_invoker = on) AS
 WITH anos AS (
         SELECT generate_series(( SELECT parametros_financeiros.ano_base_cobranca
                   FROM parametros_financeiros
                 LIMIT 1), EXTRACT(year FROM CURRENT_DATE)::integer) AS ano
        )
 SELECT s.cpf,
    s.nome,
    a.ano,
    NOT (EXISTS ( SELECT 1
           FROM financeiro_lancamentos fl
          WHERE fl.socio_cpf = s.cpf AND fl.tipo = 'anuidade'::text AND fl.competencia_ano = a.ano AND fl.status = 'pago'::text)) AS anuidade_pendente,
    COALESCE(cfg.isento, false) AS isento,
    COALESCE(cfg.liberado_pelo_presidente, false) AS liberado
   FROM socios s
     CROSS JOIN anos a
     LEFT JOIN financeiro_config_socio cfg ON cfg.cpf = s.cpf
     CROSS JOIN parametros_financeiros pf
  WHERE COALESCE(cfg.regime, pf.regime_padrao) = 'anuidade'::text AND a.ano >= (( SELECT parametros_financeiros.ano_base_cobranca
           FROM parametros_financeiros
         LIMIT 1));

CREATE OR REPLACE VIEW public.v_situacao_financeira_socio WITH (security_invoker = on) AS
 SELECT s.cpf,
    s.nome,
    s.situacao AS situacao_associativa,
    COALESCE(cfg.regime, pf.regime_padrao) AS regime,
    COALESCE(cfg.isento, false) AS isento,
    COALESCE(cfg.liberado_pelo_presidente, false) AS liberado_presidente,
    array_agg(fl.competencia_ano ORDER BY fl.competencia_ano) FILTER (WHERE fl.tipo = 'anuidade'::text AND fl.status = 'pago'::text) AS anuidades_pagas,
    max(fl.data_pagamento) AS ultimo_pagamento
   FROM socios s
     CROSS JOIN parametros_financeiros pf
     LEFT JOIN financeiro_config_socio cfg ON cfg.cpf = s.cpf
     LEFT JOIN financeiro_lancamentos fl ON fl.socio_cpf = s.cpf
  GROUP BY s.cpf, s.nome, s.situacao, cfg.regime, pf.regime_padrao, cfg.isento, cfg.liberado_pelo_presidente;
