export function getPdfFieldMappingsRequerimento(): Record<string, string[]> {
  return {
    nome: ["Nome do requerente"],
    dtnasc: ["Data de Nascimento"],
    mae: ["Nome da mãe"],
    cpf: ["CPF do requerente"],
    rg: ["RG"],
    cei: ["CEI do requerente"],
    endereco: ["Endereço do requerente"],
    num: ["Número"],
    complemento: ["Complemento"],
    cidade: ["Município"],
    uf: ["UF de residência"],
    cep: ["CEP"],
    telefone: ["Telefone do Requerente"],
    nrpub: ["Número da Portaria"],
    dtpub: ["Data da publicação da portaria"],
    area: ["Área"],
    inicio1: ["Início do Primeiro Período"],
    fim1: ["Fim do Primeiro Período"],
    inicio2: ["Início do segundo período"],
    fim2: ["Fim do segundo período"],
    especie_proibidas: ["Espécies proibidas"],
    emb_rgp: ["Número do RGP"],
    rgp_uf: ["UF"],
    nome_abreviado: ["Nome da entidade administrativa"],
    cnpj: ["CNPJ da entidade administrativa"],
    arqueacao_bruta: ["Arqueação Bruta"],
    total_tripulantes: ["Total de tripulantes"],
    cpf_proprietario_embarcacao: ["CPF do proprietário da embarcação"],
    nome_testemunha1: ["Nome da testemunha 1"],
    cpf_testemunha1: ["CPF da testemunha 1"],
    rg_testemunha1: ["RG da testemunha 1"],
    nome_testemunha2: ["Nome da testemunha 2"],
    cpf_testemunha2: ["CPF da testemunha 2"],
    rg_testemunha2: ["RG da testemunha 2"],
    data_rgp: ["Data do RGP"],
    local_assinatura: ["Município e estado de assinatura"],
    data: ["Data da assinatura"],
  };
}
export function getPdfFieldMappingsResidencia(): Record<string, string[]> {
  return {
    estado_civil: ["estado_civil"],
    numero: ["numero"],
    Email: ["Email"],
    endereco: ["endereco"],
    municipio: ["municipio"],
    local: ["local"],
    data: [
      "data",
      "Data",
      "DATA",
      "Date",
      "DATE",
      "data_doc",
      "DataDoc",
      "Data do Documento",
      "data_emissao",
      "Data de Emissão",
    ],
    bairro: ["Bairro"],
    uf: ["uf"],
    cep: ["cep"],
    telefone: ["telefone"],
    rg: ["rg"],
    cpf: ["cpf"],
    nome: ["nome"],
    nome_testemunha1: ["Nome da testemunha 1"],
    cpf_testemunha1: ["CPF da testemunha 1"],
    rg_testemunha1: ["RG da testemunha 1"],
    nome_testemunha2: ["Nome da testemunha 2"],
    cpf_testemunha2: ["CPF da testemunha 2"],
    rg_testemunha2: ["RG da testemunha 2"],
  };
}
export function getPdfFieldMappingsTermoRepresentacao(): Record<
  string,
  string[]
> {
  return {
    cidade: ["cidade"],
    data: [
      "data",
      "Data",
      "DATA",
      "Date",
      "DATE",
      "data_doc",
      "DataDoc",
      "Data do Documento",
      "data_emissao",
      "Data de Emissão",
    ],
    bairro: ["Bairro"],
    uf: ["uf"],
    cep: ["cep"],
    telefone: ["telefone"],
    rg: ["rg"],
    cpf: ["cpf"],
    nome: ["nome"],
    endereco: ["endereco"],
    local: ["local"],
    estado_civil: ["estado_civil"],
    nome_testemunha1: ["Nome da testemunha 1"],
    cpf_testemunha1: ["CPF da testemunha 1"],
    rg_testemunha1: ["RG da testemunha 1"],
    nome_testemunha2: ["Nome da testemunha 2"],
    cpf_testemunha2: ["CPF da testemunha 2"],
    rg_testemunha2: ["RG da testemunha 2"],
  };
}
